### ISSUE TITLE
[FEATURE REQUEST] Add todo API

### ISSUE THREAD

**Issue by mirland** [MostafaSolimanMO/once#12]
One of the most important features of Once java impl is the [Todo API](https://github.com/jonfinerty/Once#marking-something-as-to-do). 

Have you thought about including it? 

For example, suppose that you want to display the rate app modal after some conditions are met on a specific screen. You can achieve that easily using the todo API

**Comment by MostafaSolimanMO** [comment]
Nice one, I will consider it in the features plan
