### ISSUE TITLE
`OnceBuilder.fallback()` is always called at least one time when specified 

### ISSUE THREAD

**Issue by moazelsawaf** [MostafaSolimanMO/once#17]
Hello @MostafaSolimanMO 💙

I hope you are doing well and I wanted to thank you so much for helping the community becomes stronger 🙏🏻💙

## 📃 Issue Description

I have discovered a critical bug that causes a hard trackable problem which is always calling the `fallback()` method of `OnceBuilder()` at least one time every time the widget builds, whether the `SharedPreferences  Key` is stored or not.

After playing around with the issue I've found that the reason for this behavior is that when the `connectionstate` of the `future` is in a `waiting` state, the condition `snapshot.hasData` will always evaluate to `false`, so the `fallback()` method will always have a chance run.

Even though the bug has almost no performance issues, and also this redundant call of the `fallback()` is not being noticed because the `future` resolves very quickly, it might cause a hard trackable problem if you wanted to perform some code before the call of `fallback()` or/and `builder()`.

## 🧪 Steps of Reproduction

To reproduce the issue, I have created this minimal [gist on DartPad ](https://dartpad.dev/?id=d22322421ff5a90389fed9422ae4c2ca), try it with the following to scenarios to reproduce the same issue:
1. Run the code with an unsaved key for the SharedPreferences then check the logs, you will see the fallback() is called before the builder().
2. Run the code with a saved key for the SharedPreferences then check the logs, you will see the fallback() is called twice.

## ✅ Suggested Solution

I want to suggest the solution I made to solve the issue, which is adding an extra condition for the `FutureBuilder()` to return a `SizedBox.shrink()` when the ` ConnectionState` is `waiting` like the following:

```Dart
builder: (context, snapshot) {
  if (snapshot.connectionState == ConnectionState.waiting) {
    return const SizedBox.shrink();
  } else if (snapshot.hasData) {
    return snapshot.data!;
  } else {
    return fallback?.call() ?? const SizedBox.shrink();
  }
},
```

The returned `SizedBox()` will have no luck to be shown due to the fast resolving of the future and the code above the return of the `fallback()` will not be executed.

Thanks 🙏🏻💙

**Comment by MostafaSolimanMO** [comment]
Nice one, Moaz
Thank you for your time.
Merged!

**Comment by moazelsawaf** [comment]
You're always welcome 🙏🏻💙
