### ISSUE TITLE
Split the package into two

### ISSUE THREAD

**Issue by Ascenio** [MostafaSolimanMO/once#9]
Hello. I've noticed the package does two things: it has widgets integrated with the `once` and also does the timer logic thing. This mean the package has a unnecessary dependency on Flutter, those running Dart only can't use it. So, it would be nice to split into `once` and `once_flutter`, something like that.

**Comment by MostafaSolimanMO** [comment]
It was there [flutter_once](https://pub.dev/packages/flutter_once). But the package `once` depends on `SharedPreferences` and it depends on Flutter so the separation would not be useful unless the depending on `SharedPreferences` changed.

**Comment by Ascenio** [comment]
Oh, it does make sense. I thought the lib only managed scheduled jobs while running, I didn't know about the persistence. Maybe there should be a way the user can specify to not use any, so that it can be portable.

**Comment by MostafaSolimanMO** [comment]
We consider it and we will start working on make it available for Dart only project, Thank you!
